application: u-240b
version: 2
runtime: python
api_version: 1

handlers:

- url: /stylesheets
  static_dir: static/stylesheets

- url: /images
  static_dir: static/images

- url: /javascripts
  static_dir: static/javascripts

- url: /fonts
  static_dir: static/fonts

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: images/favicon.ico

- url: /admin
  script: main.py
  login: admin
  secure: optional

- url: /.*
  script: main.py
  secure: optional

builtins:
- datastore_admin: on
